Repository woowacourse-teams/2022-smody, pull requests merged in 2022-10, with the labels that each got.

#491 hotfix: 카카오톡 인앱 브라우저 등 기타 브라우저의 에러 해결
  frontend/public/pwaServiceWorker.js
  frontend/src/components/NotificationMessage/useNotificationMessage.ts
Labels: 프론트엔드, 에러 해결

#478 feature : (be) 랭킹 활동 및 기간 조회 기능 구현
  backend/smody/src/docs/asciidoc/api.adoc
  backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/db_support/PagingParams.java
  backend/smody/src/main/java/com/woowacourse/smody/db_support/SortSelection.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
  backend/smody/src/main/java/com/woowacourse/smody/member/controller/MemberController.java
  backend/smody/src/main/java/com/woowacourse/smody/member/dto/SearchedMemberResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/member/service/MemberService.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/controller/RankingController.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/controller/RankingPeriodController.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/Duration.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/Point.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankManager.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankingActivity.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankingPeriod.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/dto/RankingActivityResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/event/RankingPointEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/repository/RankingActivityRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/repository/RankingPeriodRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingPeriodService.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingService.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/RankingAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/controller/MemberControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/ChallengePushEventIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/ChallengePushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/EventExceptionTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/ranking/controller/RankingControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/ranking/event/RankingEventExceptionTest.java
  backend/smody/src/test/java/com/woowacourse/smody/ranking/event/RankingPointEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/ranking/event/RankingPointIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/ranking/service/RankingPeriodServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/ranking/service/RankingServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/IntegrationTest.java
  backend/smody/src/test/resources/application.properties
Labels: 백엔드, API 구현

#498 design: 디자인 피드백(프로필, 피드) 반영
  frontend/src/components/ChallengerList/index.tsx
  frontend/src/components/CheckSuccessCycle/index.tsx
  frontend/src/components/CheckSuccessCycle/type.ts
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/Record/index.tsx
  frontend/src/components/Title/index.tsx
  frontend/src/pages/FeedDetailPage/index.tsx
  frontend/src/styles/color.ts
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
Labels: 프론트엔드, UI

#499 fix: (fe) getVersionPort가 없을 때 postMessage 에러 나는 이슈 해결
  frontend/public/pwaServiceWorker.js
Labels: 프론트엔드, 에러 해결

#501 fix: (fe) CheckSuccessCycle 경로 추가
  frontend/src/components/index.ts
Labels: 프론트엔드, 에러 해결

#502 fix: (fe) 문법 에러 해결
  frontend/src/mocks/data.ts
  frontend/src/utils/index.ts
Labels: 프론트엔드, 에러 해결

#503 fix : (be) Transactional 어노테이션 추가
  backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
Labels: 에러 해결

#505 fix: 댓글 수정 시 기존 댓글 내용 가져오기, 알림 리다이렉션
  frontend/public/pwaServiceWorker.js
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CommentInput/useCommentInput.ts
  frontend/src/components/NotificationMessage/useNotificationMessage.ts
  frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts
Labels: 프론트엔드, 에러 해결

#509 refactor: (be) 알림 api 전송 scheduler에게 위임 밎 update n+1 해결
  backend/smody/src/main/java/com/woowacourse/smody/push/PushScheduler.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/CommentPushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/SubscriptionPushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/repository/PushNotificationRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
  backend/smody/src/test/java/com/woowacourse/smody/push/PushSchedulerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationServiceTest.java
Labels: 백엔드, 최적화

#512 feat: (fe) 피드 상세보기 스크롤 시 NavBar 위치 자동 조절
  frontend/public/pwaServiceWorker.js
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/FeedItem/useFeedItem.ts
  frontend/src/components/Title/index.tsx
  frontend/src/components/Title/useTitle.ts
  frontend/src/constants/css.ts
  frontend/src/hooks/useScrollDirection.ts
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/FeedDetailPage/index.tsx
Labels: 프론트엔드, UI, UI 로직

#515 feat: (fe) 챌린저 리스트 디자인 수정
  frontend/public/pwaServiceWorker.js
  frontend/src/components/ChallengerList/index.tsx
Labels: 프론트엔드, UI

#517 feat: (fe) 랭킹 기간 리스트 표기 수정
  frontend/src/components/RankingPeriodItem/useRankingPeriodItem.ts
Labels: 프론트엔드, UI

#518 feat: (fe) pwa version 올리기
  frontend/public/pwaServiceWorker.js
Labels: 프론트엔드, PWA

#519 fix : (be)필드명 변경
  backend/smody/src/main/java/com/woowacourse/smody/challenge/dto/ChallengersResponse.java
  backend/smody/src/test/java/com/woowacourse/smody/challenge/controller/ChallengeControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeServiceTest.java
Labels: 에러 해결

#520 fix: (fe) 랭킹 기간 계산 이슈 해결
  frontend/public/pwaServiceWorker.js
  frontend/src/utils/index.ts
Labels: 프론트엔드, 에러 해결, UI 로직

#524 refactor: (be) vaadin 의존성 제거
  backend/smody/build.gradle
  backend/smody/src/main/java/com/woowacourse/smody/auth/login/AuthInterceptor.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/LogLevel.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/MenuLayout.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/AdminSecurityConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/ChallengeView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/CycleDetailView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/CycleView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/DomainView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/IndexView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/LogView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/LoginView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/MemberView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/PushNotificationView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/SmodyVaddinService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinChallengeService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinCycleDetailService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinCycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinMemberService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinPushNotificationService.java
  backend/smody/src/test/java/com/woowacourse/smody/support/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/SecurityTestConfig.java
Labels: 백엔드, 리팩터링, 에러 해결

#529 refactor: (fe) 멘션 기능 파일 분리 및 리팩터링
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CommentInput/useCommentInput.ts
  frontend/src/components/CommentInput/useMention.ts
  frontend/src/components/CommentInput/usePopover.ts
  frontend/src/hooks/useMutationObserver.ts
Labels: 프론트엔드, 리팩터링

#545 feat: (fe) 네비게이션의 인증 버튼을 flat하게 변경한다
  frontend/src/assets/plus.svg
  frontend/src/components/Navbar/index.tsx
Labels: 프론트엔드, UI

#546 feat: (fe) 댓글에 공백이나 개행문만 입력하여 전송하면 발생하는 에러 해결
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CommentInput/useCommentInput.ts
Labels: 프론트엔드, UI, UI 로직

#553 feat: (fe) 에러 메세지 최신화
  frontend/src/constants/message.ts
Labels: 프론트엔드

#544 feat: (be) error 발생 시 issue 자동 생성 기능 추가
  backend/smody/src/main/java/com/woowacourse/smody/auth/api/GoogleApi.java
  backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/ControllerAdvice.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/GithubApi.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/dto/ExceptionResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/dto/IssueCreateRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/image/strategy/ImgBBImageStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/image/strategy/SmodyImageStrategy.java
  backend/smody/src/test/java/com/woowacourse/smody/exception/GithubApiTest.java
  backend/smody/src/test/java/com/woowacourse/smody/exception/UnexpectedErrorGithubIssueIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/exception/UnexpectedErrorGithubIssueTest.java
  backend/smody/src/test/java/com/woowacourse/smody/image/ImgBBImageStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/image/SmodyImageStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/IntegrationTest.java
  backend/smody/src/test/resources/application.properties
Labels: 백엔드

#563 feat: (fe) 우테코 팀프로젝트 이벤트 챌린지 페이지 및 탭 컴포넌트 구현
  frontend/src/Router.tsx
  frontend/src/assets/project_icons.png
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeDetail/index.tsx
  frontend/src/components/ChallengeDetail/type.ts
  frontend/src/components/ChallengeIcon/ChallengeIcon.stories.tsx
  frontend/src/components/ChallengeIcon/index.tsx
  frontend/src/components/ChallengeIcon/type.ts
  frontend/src/components/ChallengeInfoWithUser/index.tsx
  frontend/src/components/ChallengeInfoWithUser/useChallengeInfoWithUser.ts
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/CycleRecords/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Navbar/useNavBar.ts
  frontend/src/components/Record/index.tsx
  frontend/src/components/Record/type.ts
  frontend/src/components/SearchBar/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/SuccessModal/type.ts
  frontend/src/components/SuccessModal/useSuccessModal.ts
  frontend/src/components/Tabs/Tabs.stories.tsx
  frontend/src/components/Tabs/index.tsx
  frontend/src/components/Tabs/type.ts
  frontend/src/components/Tabs/useTabs.ts
  frontend/src/components/ThumbnailWrapper/ThumbnailWrapper.stories.tsx
  frontend/src/components/ThumbnailWrapper/index.tsx
  frontend/src/components/ThumbnailWrapper/type.ts
  frontend/src/components/index.ts
  frontend/src/constants/event.ts
  frontend/src/constants/path.ts
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/ChallengeCreatePage/index.tsx
  frontend/src/pages/ChallengePage/index.tsx
  frontend/src/pages/ChallengePage/useChallengePage.ts
  frontend/src/pages/CycleDetailPage/index.tsx
  frontend/src/pages/EventPage/components/EventChallengeItem/index.tsx
  frontend/src/pages/EventPage/components/EventChallengeItem/type.ts
  frontend/src/pages/EventPage/components/index.ts
  frontend/src/pages/EventPage/index.tsx
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/useSearchPage.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드, UI, UI 로직

#566 feat: (fe) 모바일에서 인증형식이 가려지는 에러 및 인증 페이지의 스크롤 통일
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/useCertFormPage.ts
Labels: 프론트엔드, UI, 에러 해결

#569 feat: (fe) 랭킹 등수, 포인트에 따른 레이아웃 변경 수정
  frontend/src/components/RankingItem/index.tsx
  frontend/src/mocks/data.ts
Labels: 프론트엔드, UI

#572 feat: (fe) favicon을 manifest에서 제거하고 head 내에 추가
  frontend/public/image/android-chrome-192x192-maskable.png
  frontend/public/image/android-chrome-512x512-maskable.png
  frontend/public/image/favicon-16x16.png
  frontend/public/image/favicon-32x32.png
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/pwaServiceWorker.js
Labels: 프론트엔드, PWA

#574 fix: (fe) commentInput에 remove event 하던 코드 제거
  frontend/public/pwaServiceWorker.js
  frontend/src/components/CommentInput/useMention.ts
  frontend/src/mocks/handlers/challenge.js
Labels: 프론트엔드, 에러 해결

#575 fix: (fe) useChallengeInfoWithUser에서 challengeId type 문제 해결
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/ChallengeInfoWithUser/index.tsx
Labels: 프론트엔드, 에러 해결

#560 fix : (be) 챌린지 조회할 때 `[, ]`로 검색 시 에러 해결
  backend/smody/src/main/java/com/woowacourse/smody/config/TomcatWebCustomConfig.java
Labels: 백엔드, 에러 해결

#561 feat: (be) n대의 WAS에서 스케줄러 가동 여부 유연하게 결정 구현
  backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
  backend/smody/src/main/java/com/woowacourse/smody/config/WebPushSchedulerConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/push/WebPushBatch.java
  backend/smody/src/main/java/com/woowacourse/smody/push/WebPushScheduler.java
  backend/smody/src/test/java/com/woowacourse/smody/push/WebPushBatchTest.java
Labels: 백엔드, 에러 해결

#558 feature: (be) 나의 보낸 알림 모두 삭제 기능 구현
  backend/smody/src/docs/asciidoc/api.adoc
  backend/smody/src/main/java/com/woowacourse/smody/push/controller/PushNotificationController.java
  backend/smody/src/main/java/com/woowacourse/smody/push/repository/PushNotificationRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationApiService.java
  backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
  backend/smody/src/main/resources/static/docs/api.html
  backend/smody/src/test/java/com/woowacourse/smody/push/controller/PushNotificationControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationApiServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationServiceTest.java
Labels: 백엔드, API 구현

#559 feat : (be) 챌린지 필터링 기능 구현
  backend/smody/src/main/java/com/woowacourse/smody/challenge/domain/ChallengingRecords.java
  backend/smody/src/main/java/com/woowacourse/smody/challenge/repository/DynamicChallengeRepositoryImpl.java
  backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
  backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeService.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/repository/CycleRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/db_support/CursorPaging.java
  backend/smody/src/main/java/com/woowacourse/smody/db_support/PagingParams.java
  backend/smody/src/main/java/com/woowacourse/smody/db_support/SortSelection.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
  backend/smody/src/test/java/com/woowacourse/smody/challenge/repository/ChallengeRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
Labels: 백엔드, API 구현

#578 feat: (fe) 페이지가 변경되면 알람창을 자동으로 닫도록 구현
  frontend/src/components/Dropdown/useDropdown.ts
  frontend/src/constants/css.ts
Labels: 프론트엔드, UI, UI 로직

#580 feat: (fe) SubscriptionButton 리팩터링
  frontend/public/pwaServiceWorker.js
  frontend/src/components/SubscriptionButton/index.tsx
  frontend/src/components/SubscriptionButton/type.ts
  frontend/src/components/SubscriptionButton/useSubscriptionButton.ts
  frontend/src/constants/event.ts
  frontend/src/mocks/data.ts
Labels: 프론트엔드, UI 로직

#584 feat: (fe) 이벤트 챌린지 설명 추가
  frontend/public/pwaServiceWorker.js
  frontend/src/pages/EventPage/index.tsx
Labels: 프론트엔드, UI

#588 feat: (fe) contentPage에 suspense 추가
  frontend/src/pages/ChallengePage/index.tsx
Labels: 프론트엔드, UI

#589 feat: (fe) 챌린지 정렬 방법 추가
  frontend/src/Router.tsx
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/constants/path.ts
  frontend/src/constants/storage.ts
  frontend/src/pages/ChallengePage/index.tsx
  frontend/src/pages/PopularChallengePage/index.tsx
  frontend/src/pages/PopularChallengePage/usePopularChallengePage.ts
  frontend/src/pages/RandomChallengePage/index.tsx
  frontend/src/pages/RandomChallengePage/useRandomChallengePage.ts
  frontend/src/pages/index.tsx
  frontend/src/pwa/indexedDB.js
Labels: 프론트엔드, UI, API 연결, UI 로직

#591 feat: (fe) 버튼을 눌렀을 때 모든 알림이 지워지도록 구현
  frontend/src/apis/pushNotificationApi/api.ts
  frontend/src/apis/pushNotificationApi/index.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/NotificationMessage/index.tsx
  frontend/src/components/SubscriptionButton/index.tsx
  frontend/src/components/SubscriptionButton/useSubscriptionButton.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/push.js
  frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts
Labels: 프론트엔드, UI, API 연결, UI 로직

#596 feat: (fe) 멘션을 하고 멤버 팝오버 UI가 닫히지 않는 이슈
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CommentInput/useCommentInput.ts
  frontend/src/components/CommentInput/useMention.ts
  frontend/src/components/CommentInput/usePopover.ts
  frontend/src/utils/index.ts
Labels: 프론트엔드, UI, 에러 해결, UI 로직

#586 fix : (be) 회원 탈퇴 시 외래키 제약조건 에러 수정
  backend/smody/src/main/java/com/woowacourse/smody/comment/domain/Comment.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleDetail.java
  backend/smody/src/main/java/com/woowacourse/smody/member/service/MemberService.java
  backend/smody/src/main/java/com/woowacourse/smody/push/WebPushBatch.java
  backend/smody/src/main/java/com/woowacourse/smody/push/domain/PushNotification.java
  backend/smody/src/main/java/com/woowacourse/smody/push/domain/PushSubscription.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankingActivity.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberApiServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
Labels: 에러 해결

#594 test : (be) Member, Challenge, Push 도메인 서비스 계층 테스트 추가
  backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
  backend/smody/src/main/java/com/woowacourse/smody/push/WebPushBatch.java
  backend/smody/src/main/java/com/woowacourse/smody/push/api/WebPushApi.java
  backend/smody/src/main/java/com/woowacourse/smody/push/controller/PushSubscriptionController.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/ChallengePushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/repository/PushNotificationRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
  backend/smody/src/main/java/com/woowacourse/smody/push/service/PushSubscriptionApiService.java
  backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberApiServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/WebPushBatchTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/controller/PushSubscriptionControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationApiServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/service/PushSubscriptionServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/IntegrationTest.java
Labels: 백엔드, 테스트

#600 remove: (fe) 불필요한 로더 및 바벨 등의 라이브러리들을 삭제하고 yarn.lock 다시 생성
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
Labels: 프론트엔드

#601 feat: (fe) 댓글 멘션 알림 툴팁 추가
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/Tooltip/index.tsx
  frontend/src/components/Tooltip/type.ts
Labels: 프론트엔드, UI

#604 feat: (fe) feedItem이 피드 상세 페이지일 경우 이미지 높이를 100%로 변경하여 모두 보기
  frontend/src/components/@shared/ModalOverlay/index.tsx
  frontend/src/components/@shared/ModalOverlay/type.ts
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/FeedItem/type.ts
  frontend/src/mocks/data.ts
Labels: 프론트엔드, UI

#608 feat: (fe) 탭과 알림 모두 삭제에서 refetch가 안되는 에러
  frontend/public/pwaServiceWorker.js
  frontend/src/apis/challengeApi/index.ts
  frontend/src/components/SubscriptionButton/useSubscriptionButton.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengePage/index.tsx
  frontend/src/pages/RandomChallengePage/index.tsx
Labels: 프론트엔드, UI, 에러 해결, UI 로직

#610 feat: (fe) 이벤트 챌린지 추가(땡쿠)
  frontend/src/constants/event.ts
Labels: 프론트엔드

#613 Feature/fe/a11y
  frontend/src/Layout/index.tsx
  frontend/src/components/@shared/BottomSheet/index.tsx
  frontend/src/components/@shared/ModalOverlay/index.tsx
  frontend/src/components/Bell/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertItem/useCertItem.ts
  frontend/src/components/ChallengeIcon/index.tsx
  frontend/src/components/CheckCircles/index.tsx
  frontend/src/components/DarkModeButton/index.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Dropdown/type.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/SnackBar/index.tsx
  frontend/src/components/SubscriptionButton/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/SuccessModal/useSuccessModal.ts
  frontend/src/components/Tabs/index.tsx
  frontend/src/components/Title/index.tsx
  frontend/src/hooks/useImageInput.tsx
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/useCertFormPage.ts
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeCreatePage/index.tsx
  frontend/src/pages/ChallengeCreatePage/useChallengeCreatePage.ts
Labels: 프론트엔드, 접근성

#615 feat: (fe) 상세 페이지에서 사진에 cursor: pointer를 주도록 구현
  frontend/public/pwaServiceWorker.js
  frontend/src/Layout/index.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/FeedItem/type.ts
Labels: 프론트엔드, UI

#617 hotfix: 아웃렛 아웃라인 파란선 없애기
  frontend/public/pwaServiceWorker.js
  frontend/src/Layout/index.tsx
  frontend/src/pwa/indexedDB.js
Labels: 프론트엔드

#618 fix: (fe) 멘션하고 뒤에 쓴 글을 수정하려고 지우면 전체 삭제됨 에러 해결
  frontend/public/manifest.json
  frontend/public/pwaServiceWorker.js
  frontend/src/components/CommentInput/usePopover.ts
Labels: 프론트엔드, 에러 해결, UI 로직, PWA

#620 feat: (fe) 구글플레이스토어 인증을 위한 assetlinks 코드 추가
  frontend/public/assetlinks.json
  frontend/public/pwaServiceWorker.js
  frontend/webpack.config.js
Labels: 프론트엔드, PWA

#627 docs: 로컬 실행 방법 추가
  README.md
  frontend/public/pwaServiceWorker.js
Labels: 백엔드, 프론트엔드, 환경 설정, 문서화

#629 fix: (fe) 푸시알림 아이콘 뱃지 이미지 적용 및 미지원 브라우저에 대응한 BroadcastChannel 재적용
  .vscode/settings.json
  frontend/public/manifest.json
  frontend/public/pwaServiceWorker.js
  frontend/src/components/NotificationMessage/useNotificationMessage.ts
Labels: 프론트엔드, 에러 해결, PWA

#631 feat: (fe) 로그인 후 Feed 페이지로 리다이렉션 되도록 구현
  frontend/src/hooks/useAuth.ts
Labels: 프론트엔드, 에러 해결
