Repository woowacourse-teams/2022-smody, pull requests merged in 2022-09, with the labels that each got.

#375 test: (be) 테스트에서 롤백을 위한 @Transactional 제거
  backend/smody/src/main/java/com/woowacourse/smody/image/strategy/ImgBBImageStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/member/domain/Member.java
  backend/smody/src/main/java/com/woowacourse/smody/push/domain/PushSubscription.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/CommentPushStrategy.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/AcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/comment/service/CommentServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleDetailRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/feed/repository/FeedRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/feed/service/FeedQueryServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/PushSchedulerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/repository/PushSubscriptionRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/ChallengePushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/CommentPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/IntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/RepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/ResourceFixture.java
  backend/smody/src/test/java/com/woowacourse/smody/support/isoloation/SmodyDatabaseManager.java
  backend/smody/src/test/java/com/woowacourse/smody/support/isoloation/SmodyTestEnvironmentExtension.java
  backend/smody/src/test/resources/data.sql
  backend/smody/src/test/resources/truncate.sql
Labels: 백엔드, 리팩터링, 테스트

#376 feat: (fe) 오프라인 환경에서 웹페이지 사용 가능(캐시 스토리지, indexedDB)
  frontend/public/image/screenshot-0.png
  frontend/public/image/screenshot-1.png
  frontend/public/image/screenshot-2.png
  frontend/public/image/screenshot-3.png
  frontend/public/image/screenshot-4.png
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/pushServiceWorker.js
  frontend/public/pwaServiceWorker.js
  frontend/src/components/CardGridContainer/useCardGridContainer.ts
  frontend/src/components/Dropdown/useDropdown.ts
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/NotificationMessage/useNotificationMessage.ts
  frontend/src/components/Profile/useProfile.ts
  frontend/src/components/SubscriptionButton/index.tsx
  frontend/src/hooks/useSubscribe.ts
  frontend/src/index.tsx
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/CertPage/useCertPage.ts
  frontend/src/pages/FeedPage/index.tsx
  frontend/src/pages/FeedPage/useFeedPage.ts
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/useSearchPage.ts
  frontend/src/push/registerPushServiceWorker.ts
  frontend/src/pwa/badge.js
  frontend/src/pwa/indexedDB.js
  frontend/src/pwa/pushStatus.ts
  frontend/src/pwa/registerPwaServiceWorker.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 프론트엔드, 최적화, PWA

#383 fix: (fe) 피드와 댓글 UI에서 텍스트 넘치는 이슈 해결
  frontend/src/components/CommentItem/index.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/mocks/data.ts
Labels: 프론트엔드, 에러 해결

#387 chore : perforMon관련 의존성 추가
  backend/smody/build.gradle
Labels: 인프라

#388 refactor: (fe) 서비스워커 오프라인 관련 코드 리팩터링
  frontend/public/pwaServiceWorker.js
Labels: 프론트엔드, PWA

#389 chore : perforMon관련 의존성 제거
  backend/smody/build.gradle
  backend/smody/src/main/resources/static/docs/api.html
Labels: 인프라

#385 fix: (fe) 피드 상세 페이지에서 챌린지 이름 관련 이슈 해결
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CycleDetailItem/index.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/FeedItem/type.ts
  frontend/src/components/FeedItem/useFeedItem.ts
  frontend/src/mocks/data.ts
  frontend/src/pages/FeedDetailPage/index.tsx
  frontend/src/pages/FeedPage/index.tsx
Labels: 프론트엔드, 에러 해결

#392 feat: (fe) 웹 성능 최적화
  frontend/package.json
  frontend/public/image/android-chrome-192x192.png
  frontend/public/image/android-chrome-512x512.png
  frontend/public/image/apple-touch-icon.png
  frontend/public/image/favicon-16x16.png
  frontend/public/image/favicon-32x32.png
  frontend/public/image/screenshot-0.png
  frontend/public/image/screenshot-1.png
  frontend/public/image/screenshot-2.png
  frontend/public/image/screenshot-3.png
  frontend/public/image/screenshot-4.png
  frontend/public/index.html
  frontend/src/assets/service_example.webp
  frontend/src/components/Challenger/index.tsx
  frontend/src/components/CommentItem/index.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/global.d.ts
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 프론트엔드, 최적화

#393 fix: (fe) 피드 상세 페이지 챌린지 이름 관련 누락된 코드 반영
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/FeedItem/index.tsx
Labels: 프론트엔드, 에러 해결

#400 fix: (fe) CycleDetailItem description 잘림 문제 해결
  frontend/src/components/CycleDetailItem/index.tsx
Labels: 프론트엔드, UI, 에러 해결

#395 feat: (fe) 챌린지 이름 입력 시 자동 검색되는 기능 구현
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/SearchBar/SearchBar.stories.tsx
  frontend/src/components/SearchBar/index.tsx
  frontend/src/components/SearchBar/type.ts
  frontend/src/constants/domain.ts
  frontend/src/constants/regex.ts
  frontend/src/hooks/useDebounce.ts
  frontend/src/hooks/useSnackBar.ts
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/useSearchPage.ts
Labels: 프론트엔드, 최적화, API 연결, UI 로직

#399 feature: (be) 알림 비동기 처리
  backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
  backend/smody/src/main/java/com/woowacourse/smody/comment/service/CommentService.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/ChallengePushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/CommentPushStrategy.java
  backend/smody/src/test/java/com/woowacourse/smody/comment/domain/CommentTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/controller/CycleControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/CycleTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleDetailRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/image/ImgBBImageStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/ChallengePushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/EventExceptionTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/ChallengePushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/SubscriptionPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/ResourceFixture.java
Labels: 백엔드, 리팩터링, 최적화, 문서화

#405 feature: (be) Feed에 progressCount 추가
  backend/smody/src/main/java/com/woowacourse/smody/feed/domain/Feed.java
  backend/smody/src/main/java/com/woowacourse/smody/feed/dto/FeedResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/feed/repository/FeedDynamicRepositoryImpl.java
  backend/smody/src/main/java/com/woowacourse/smody/feed/repository/FeedRepository.java
  backend/smody/src/test/java/com/woowacourse/smody/feed/controller/FeedControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/feed/service/FeedQueryServiceTest.java
Labels: 백엔드, API 구현

#404 feat: (fe) 피드 페이지에서 progressCount 정보 추가
  frontend/src/commonType.ts
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/FeedItem/type.ts
  frontend/src/components/FeedItem/useFeedItem.ts
  frontend/src/mocks/data.ts
  frontend/src/pages/FeedDetailPage/index.tsx
Labels: 프론트엔드, UI, API 연결, UI 로직

#408 feat: (fe) 인증 성공 시 인증 기록을 공유할 수 있는 기능 구현
  frontend/public/pwaServiceWorker.js
  frontend/src/Router.tsx
  frontend/src/assets/smody_icon.png
  frontend/src/components/Record/index.tsx
  frontend/src/components/Record/type.ts
  frontend/src/components/Record/useRecord.ts
  frontend/src/components/ShareButton/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/SuccessModal/useSuccessModal.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/useShare.ts
  frontend/src/pages/CycleDetailPage/index.tsx
  frontend/src/pages/CycleDetailSharePage/index.tsx
  frontend/src/pages/CycleDetailSharePage/type.ts
  frontend/src/pages/CycleDetailSharePage/useCycleDetailSharePage.ts
  frontend/src/pages/index.tsx
  frontend/src/utils/index.ts
Labels: 프론트엔드, UI, API 연결, UI 로직, PWA

#409 refactor: (fe) indexedDB 클래스에 putPost 메서드 추가하여 리팩터링
  frontend/public/pwaServiceWorker.js
  frontend/src/components/CardGridContainer/useCardGridContainer.ts
  frontend/src/pages/CertPage/useCertPage.ts
  frontend/src/pages/FeedPage/useFeedPage.ts
  frontend/src/pages/SearchPage/useSearchPage.ts
  frontend/src/pwa/indexedDB.js
Labels: 프론트엔드, 리팩터링, 에러 해결, PWA

#416 fix: (be) 로그 색깔 제외해서 로그 생성 최적화
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/LogLevel.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/LogView.java
Labels: 백엔드, 에러 해결

#418 fix: (fe) 이미지 캐싱 전략을 Cache First에서 Network First로 변경
  frontend/public/pwaServiceWorker.js
Labels: 프론트엔드, 에러 해결, PWA

#422 hotfix: (be) batch 쿼리 삭제
  backend/smody/src/main/java/com/woowacourse/smody/BatchUpdateExecutor.java
  backend/smody/src/main/java/com/woowacourse/smody/DataBatch.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleDetail.java
Labels: 백엔드, 에러 해결

#426 refactor: (fe) 에러바운더리 리팩터링 및 네트워크 에러 시 스낵바
  frontend/public/pwaServiceWorker.js
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/FeedPage/index.tsx
  frontend/src/pages/SearchPage/index.tsx
Labels: 프론트엔드, 리팩터링, 에러 해결

#429 멤버의 default introduction 수정
  backend/smody/src/main/java/com/woowacourse/smody/member/domain/Member.java
Labels: 백엔드

#431 fix: (fe) 로그인 후 리다이렉션되는 url 변경
  frontend/src/hooks/useAuth.ts
  frontend/src/mocks/handlers/auth.js
Labels: 프론트엔드, 에러 해결

#433 feat: (fe) progressImage 레이지 로딩 제거 및 이미지 압축률 올리기
  frontend/src/components/FeedItem/index.tsx
  frontend/src/hooks/useImageInput.tsx
Labels: 프론트엔드, 최적화

#438 fix: (fe) MessageChannel API로 변경
  frontend/public/pwaServiceWorker.js
  frontend/src/components/NotificationMessage/useNotificationMessage.ts
Labels: 프론트엔드, 에러 해결, PWA

#442 fix: 사용하지 않는 myChallenge 관련 indexedDB 코드 삭제
  frontend/src/components/CardGridContainer/useCardGridContainer.ts
  frontend/src/pwa/indexedDB.js
Labels: 프론트엔드, 에러 해결, PWA

#443 Version 3.1.1 배포
  frontend/src/components/CardGridContainer/useCardGridContainer.ts
  frontend/src/pwa/indexedDB.js
Labels: 프론트엔드, 에러 해결, PWA

#453 refactor: (fe) 이미지 압축 훅에서 압축률 옵션을 매개변수로 분리
  frontend/public/pwaServiceWorker.js
  frontend/src/components/Challenger/index.tsx
  frontend/src/components/CommentItem/index.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/hooks/useImageInput.tsx
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/src/pwa/indexedDB.js
Labels: 프론트엔드, UI, 리팩터링, 최적화, UI 로직

#454 fix: (be) 진행 중인 사이클에서 성공횟수 오류 수정
  backend/smody/src/main/java/com/woowacourse/smody/cycle/repository/DynamicCycleRepositoryImpl.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
Labels: 백엔드, 에러 해결

#460 feat: 타입 유틸 분리 및 npm 라이브러리에 발행
  frontend/lib/.gitignore
  frontend/lib/.npmignore
  frontend/lib/README.md
  frontend/lib/__tests__/index.test-d.ts
  frontend/lib/__tests__/test-util.ts
  frontend/lib/jest.config.js
  frontend/lib/jest.config.tsd.js
  frontend/lib/package-lock.json
  frontend/lib/package.json
  frontend/lib/src/index.ts
  frontend/lib/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/commonType.ts
  frontend/src/styles/type.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 프론트엔드, 테스트, 타입스크립트

#462 feat: (fe) 챌린저 리스트 밑에 padding 넣기
  frontend/src/mocks/data.ts
  frontend/src/pages/ChallengeDetailPage/index.tsx
Labels: 프론트엔드, 에러 해결

#465 feat: (fe) indexedDB의 name들을 constants로 분리
  frontend/src/constants/storage.ts
  frontend/src/pages/CertPage/useCertPage.ts
  frontend/src/pages/FeedPage/useFeedPage.ts
  frontend/src/pages/SearchPage/useSearchPage.ts
  frontend/src/pwa/indexedDB.js
Labels: 프론트엔드, 리팩터링

#467 refactor: (fe) children이 사용된 컴포넌트에 PropsWithChildren 적용
  frontend/src/components/@shared/ModalOverlay/index.tsx
  frontend/src/components/@shared/ModalOverlay/type.ts
  frontend/src/components/BottomSheet/index.tsx
  frontend/src/components/BottomSheet/type.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Dropdown/type.ts
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/components/ErrorBoundary/type.ts
  frontend/src/components/InfiniteScroll/index.tsx
  frontend/src/components/InfiniteScroll/type.ts
  frontend/src/components/LinkText/index.tsx
  frontend/src/components/LinkText/type.ts
  frontend/src/components/ScrollToTop/index.tsx
  frontend/src/components/ScrollToTop/type.ts
  frontend/src/components/Title/index.tsx
  frontend/src/components/Title/type.ts
Labels: 프론트엔드, 리팩터링

#463 refactor: (be) 알림이 발생하는 비즈니스 이벤트 세분화
  backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
  backend/smody/src/main/java/com/woowacourse/smody/comment/domain/CommentCreateEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/comment/service/CommentService.java
  backend/smody/src/main/java/com/woowacourse/smody/config/AsyncConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleCreateEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleProgressEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/db_support/DynamicQuery.java
  backend/smody/src/main/java/com/woowacourse/smody/push/domain/PushSubscribeEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/ChallengePushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/CommentPushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/SubscriptionPushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/service/PushSubscriptionService.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/PushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/ChallengeView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/CycleDetailView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/CycleView.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/CommentAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/FeedAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/auth/service/OauthServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/challenge/controller/ChallengeControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/comment/controller/CommentControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/comment/service/CommentServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/CycleTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleDetailRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/feed/controller/FeedControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/feed/service/FeedQueryServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/ChallengePushEventIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/ChallengePushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/EventExceptionTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventIntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/ChallengePushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/CommentPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/SubscriptionPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/IntegrationTest.java
  backend/smody/src/test/resources/application.properties
Labels: 백엔드, 리팩터링, 최적화

#468 feat : (be) 멘션 시 대응되는 사용자들의 목록을 가져오는 기능 구현
  backend/smody/src/main/java/com/woowacourse/smody/member/controller/MemberController.java
  backend/smody/src/main/java/com/woowacourse/smody/member/dto/MentionResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/member/repository/DynamicMemberRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/member/repository/DynamicMemberRepositoryImpl.java
  backend/smody/src/main/java/com/woowacourse/smody/member/repository/MemberRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/member/service/MemberService.java
  backend/smody/src/main/resources/static/docs/api.html
  backend/smody/src/test/java/com/woowacourse/smody/member/controller/MemberControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/ResourceFixture.java
Labels: 백엔드, API 구현

#477 feat: (fe) msw headers 오류
  frontend/src/mocks/utils.js
Labels: 프론트엔드, 에러 해결, UI 로직
