Repository woowacourse-teams/2022-smody, pull requests merged in 2022-08, with the labels that each got.

#166 feat: (fe) 이미지 압축 및 업로드 기능 구현(useImageInput 훅), 프로필
  frontend/package.json
  frontend/src/Router.tsx
  frontend/src/apis/oAuthApi/api.ts
  frontend/src/apis/oAuthApi/index.ts
  frontend/src/hooks/useImageInput.tsx
  frontend/src/mocks/handlers/auth.js
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/yarn.lock
Labels: 프론트엔드, API 연결, UI 로직

#171 feat: (fe) 로딩 로직 구현 및 UI 적용
  frontend/package.json
  frontend/src/Layout/index.tsx
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/hooks/auth/useAuth.ts
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/NotFoundPage/index.tsx
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/VocPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/queryClient.ts
  frontend/src/styles/color.ts
  frontend/src/styles/theme.ts
  frontend/yarn.lock
Labels: 프론트엔드, UI, UI 로직

#172 feat: (fe) theme 관련 useContext 커스텀 훅 분리
  frontend/src/Layout/index.tsx
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/CheckCircles/index.tsx
  frontend/src/components/EmptyContent/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/SnackBar/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/Timer/useTimer.tsx
  frontend/src/components/UserWithdrawalModal/index.tsx
  frontend/src/hooks/useThemeContext.ts
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/src/pages/VocPage/index.tsx
Labels: 프론트엔드, 리팩터링, UI 로직

#173 refactor: (fe) query key 상수화
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/constants.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/apis/oAuthApi/index.ts
Labels: 프론트엔드, 리팩터링

#174 remove: (fe) authApi 등 관련 레거시 코드 삭제
  frontend/src/Router.tsx
  frontend/src/apis/authApi/api.ts
  frontend/src/apis/authApi/index.ts
  frontend/src/apis/authApi/type.ts
  frontend/src/apis/index.ts
  frontend/src/assets/cute_cat_with_smody.png
  frontend/src/assets/email_icon.svg
  frontend/src/assets/person_icon.svg
  frontend/src/assets/pw_icon.svg
  frontend/src/assets/visibility_icon.svg
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ErrorBoundary/index.ts
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/api/type.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/usePostJoinChallenge.ts
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/VocPage/index.tsx
Labels: 프론트엔드, 리팩터링

#175 refactor: (fe) FlexBox 컴포넌트 타입 수정
  frontend/src/Layout/index.tsx
  frontend/src/components/@shared/FlexBox/type.ts
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/CheckCircles/index.tsx
  frontend/src/components/EmptyContent/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/SnackBar/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/Timer/index.tsx
  frontend/src/components/UserWithdrawalModal/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/pages/VocPage/index.tsx
Labels: 프론트엔드, 리팩터링

#179 feat: (fe) 사이클 상세 조회 페이지 UI 구현
  frontend/src/Layout/index.tsx
  frontend/src/Router.tsx
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/commonType.ts
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/@shared/FlexBox/type.ts
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/CycleDetailItem/CycleDetailItem.stories.tsx
  frontend/src/components/CycleDetailItem/index.tsx
  frontend/src/components/CycleDetailItem/type.ts
  frontend/src/components/CycleDetailList/index.tsx
  frontend/src/components/CycleDetailList/type.ts
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/constants/style.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/CycleDetailPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/utils/index.ts
Labels: 프론트엔드, UI

#181 feat: (fe) 인증 Form 페이지 UI 구현
  frontend/src/Router.tsx
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/apis/oAuthApi/api.ts
  frontend/src/apis/oAuthApi/index.ts
  frontend/src/apis/oAuthApi/type.ts
  frontend/src/assets/close.svg
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/@shared/ModalOverlay/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertItem/type.ts
  frontend/src/components/CheckCircles/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/SuccessModal/type.ts
  frontend/src/components/Title/Title.stories.tsx
  frontend/src/components/Title/index.tsx
  frontend/src/components/Title/type.ts
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useImageInput.tsx
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/type.ts
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/CycleDetailPage/index.tsx
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/src/pages/index.tsx
Labels: 프론트엔드, UI, API 연결

#183 fix: (fe) 프로필 이미지 수정 후 새로 바뀐 이미지가 바로 안보이는 문제 해결
  frontend/src/pages/ProfileEditPage/index.tsx
Labels: 프론트엔드, 에러 해결

#185 feat: (fe) 인증하기 페이지 추가 기능 구현
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/type.ts
Labels: 프론트엔드, 리팩터링

#191 feat: (fe) 챌린지 도전 여부에 따라 도전 버튼 활성화 여부 판단 기능 구현
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/commonType.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengeDetailPage/index.tsx
Labels: 프론트엔드

#192 feat: (fe) google oAuth 로그인 시 url에 code 지우는 기능 구현
  frontend/src/hooks/useAuth.ts
Labels: 프론트엔드, 리팩터링, UI 로직

#193 fix: (fe) Header와 Navbar CSS 문제 해결
  frontend/src/Layout/index.tsx
  frontend/src/Layout/type.ts
  frontend/src/components/@shared/ModalOverlay/index.tsx
  frontend/src/components/FixedButton/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/SnackBar/index.tsx
  frontend/src/components/UnderLineText/index.tsx
  frontend/src/constants/css.ts
Labels: 프론트엔드, UI, 에러 해결

#196 fix : (be) 글과 사진으로 인증 시 동시성 이슈 해결
  backend/smody/src/main/java/com/woowacourse/smody/repository/CycleRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
  backend/smody/src/test/resources/data.sql
Labels: 백엔드, 에러 해결

#198 feat: (fe) LoadingButton 컴포넌트 구현
  frontend/src/assets/loading_dots.svg
  frontend/src/components/LoadingButton/LoadingButton.stories.tsx
  frontend/src/components/LoadingButton/index.tsx
  frontend/src/components/LoadingButton/type.ts
  frontend/src/components/index.ts
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/ProfileEditPage/index.tsx
Labels: 프론트엔드, UI

#200 feat: (fe) CertForm 접근 경로 제거
  frontend/src/Router.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/constants/path.ts
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/type.ts
Labels: 프론트엔드, UI

#201 refactor: (be) 설정 파일 개선
  backend/smody/.gitignore
  backend/smody/package-lock.json
  backend/smody/src/test/resources/application.yml
Labels: 백엔드

#202 feat: 리워드 기준을 1로 낮춤
  frontend/src/components/SuccessModal/index.tsx
Labels: 프론트엔드, UI

#205 fix: (be) 빌드 실패 원인 제거
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeQueryService.java
  backend/smody/src/main/resources/application.properties
  backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
  backend/smody/src/test/resources/data.sql
Labels: 백엔드, 에러 해결, 테스트

#206 feat: (fe) Jest를 이용한 react query 자동화 테스트 환경설정 및 테스트 작성(1)
  frontend/babel.config.js
  frontend/jest.config.ts
  frontend/package.json
  frontend/src/__test__/MockIntersectionObserver.ts
  frontend/src/__test__/certPage.test.tsx
  frontend/src/__test__/profilePage.test.tsx
  frontend/src/__test__/searchPage.test.tsx
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/constants/path.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/fileMock.js
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/matchMedia.ts
  frontend/src/mocks/server.ts
  frontend/src/pages/index.tsx
  frontend/src/queryClient.ts
  frontend/src/setupTests.ts
  frontend/src/utils/testUtils.tsx
  frontend/yarn.lock
Labels: 프론트엔드, 테스트

#208 fix: (be) .gitignore
  backend/smody/.gitignore
  backend/smody/gradlew
  backend/smody/src/main/resources/application.properties
Labels: 백엔드, 에러 해결

#212 fix: (fe) 인증 시 description 기본 값 전달하도록 수정
  frontend/src/pages/CertFormPage/index.tsx
Labels: 프론트엔드, 에러 해결

#217 refactor: (fe) 컴포넌트에서 UI 로직을 페이지 커스텀훅으로 분리(1)
  frontend/src/components/Profile/index.tsx
  frontend/src/components/Profile/useProfile.ts
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/SuccessModal/type.ts
  frontend/src/components/SuccessModal/useSuccessModal.ts
  frontend/src/components/Timer/index.tsx
  frontend/src/components/Title/index.tsx
  frontend/src/components/Title/type.ts
  frontend/src/components/Title/useTitle.ts
  frontend/src/components/UserWithdrawalModal/index.tsx
  frontend/src/components/UserWithdrawalModal/type.ts
  frontend/src/components/UserWithdrawalModal/useUserWithdrawalModal.ts
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/useCertFormPage.ts
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/CertPage/useCertPage.ts
Labels: 프론트엔드, 리팩터링

#218 refactor: 컴포넌트에서 UI 로직을 페이지 커스텀훅으로 분리(2)
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeItem/type.ts
  frontend/src/components/ChallengeList/ChallengeList.stories.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/ChallengeList/type.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/useHeader.ts
  frontend/src/components/InfiniteScroll/index.tsx
  frontend/src/components/InfiniteScroll/type.ts
  frontend/src/components/Input/index.tsx
  frontend/src/components/Input/useInput.ts
  frontend/src/components/LandingNavigation/index.tsx
  frontend/src/components/LandingNavigation/type.ts
  frontend/src/components/LoadingButton/index.tsx
  frontend/src/components/LoadingSpinner/index.tsx
  frontend/src/components/Logo/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Navbar/useNavBar.ts
  frontend/src/components/PrivateOutlet/index.tsx
  frontend/src/components/PrivateOutlet/type.ts
  frontend/src/components/index.ts
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/useSearchPage.ts
Labels: 프론트엔드, 리팩터링

#225 feat: 기존 API 수정 및 emoji를 백엔드에서 가져오도록 수정
  frontend/src/Router.tsx
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertItem/type.ts
  frontend/src/components/CertItem/useCertItem.ts
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeItem/type.ts
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/SuccessModal/type.ts
  frontend/src/components/SuccessModal/useSuccessModal.ts
  frontend/src/mocks/data.ts
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/type.ts
  frontend/src/pages/CertFormPage/useCertFormPage.ts
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/useChallengeDetailPage.ts
  frontend/src/pages/CycleDetailPage/index.tsx
  frontend/src/utils/emoji.js
Labels: 프론트엔드, API 연결, UI 로직

#233 feat: (fe) 상세 챌린지 화면에서 참여자 목록 추가
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/apis/constants.ts
  frontend/src/components/ChallengeDetail/index.tsx
  frontend/src/components/ChallengeDetail/type.ts
  frontend/src/components/Challenger/Challenger.stories.tsx
  frontend/src/components/Challenger/index.tsx
  frontend/src/components/Challenger/type.ts
  frontend/src/components/ChallengerList/index.tsx
  frontend/src/components/ChallengerList/type.ts
  frontend/src/components/ChallengerList/useChallengerList.ts
  frontend/src/components/EmptyContent/index.tsx
  frontend/src/components/EmptyContent/type.ts
  frontend/src/components/index.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengeDetailPage/index.tsx
Labels: 프론트엔드, UI, API 연결, UI 로직

#241 feat: (fe) 해와 달 디자인의 다크모드 토글 버튼 추가
  frontend/public/manifest.json
  frontend/public/mockServiceWorker.js
  frontend/public/serviceWorker.js
  frontend/src/Router.tsx
  frontend/src/components/DarkModeButton/DarkModeButton.stories.tsx
  frontend/src/components/DarkModeButton/index.tsx
  frontend/src/components/DarkModeButton/type.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/index.ts
  frontend/src/index.tsx
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/push.js
  frontend/src/pages/TestPage/index.tsx
  frontend/src/pages/index.tsx
Labels: 프론트엔드, UI

#243 feature: (fe) 피드 컴포넌트 개발 및 피드 전체 조회 API 연결
  frontend/src/Router.tsx
  frontend/src/apis/constants.ts
  frontend/src/apis/feedApi/api.ts
  frontend/src/apis/feedApi/index.ts
  frontend/src/apis/feedApi/type.ts
  frontend/src/commonType.ts
  frontend/src/components/FeedItem/FeedItem.stories.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/FeedItem/type.ts
  frontend/src/components/FeedItem/useFeedItem.ts
  frontend/src/components/index.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/feed.js
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/FeedPage/index.tsx
  frontend/src/pages/FeedPage/useFeedPage.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드, UI, API 연결

#244 feat: (fe) 챌린지 생성 UI 구현 및 API 연결
  frontend/src/Router.tsx
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/components/BottomSheet/index.tsx
  frontend/src/components/BottomSheet/type.ts
  frontend/src/components/Input/index.tsx
  frontend/src/components/Input/type.ts
  frontend/src/components/Navbar/useNavBar.ts
  frontend/src/components/ThumbnailWrapper/index.tsx
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/constants/style.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengeCreatePage/index.tsx
  frontend/src/pages/ChallengeCreatePage/type.ts
  frontend/src/pages/ChallengeCreatePage/useChallengeCreatePage.ts
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/useSearchPage.ts
  frontend/src/pages/index.tsx
  frontend/src/utils/validator.ts
Labels: 프론트엔드, UI, API 연결, UI 로직

#248 refactor : (be) Vaadin 리팩터링
  backend/smody/src/main/java/com/woowacourse/smody/auth/AuthInterceptor.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Progress.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengesResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/image/ImgBBImageStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/CycleRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/MenuLayout.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/AdminSecurityConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/ChallengeView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/CycleView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/DomainView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/IndexView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/LogView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/LoginView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/MemberView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/SmodyVaddinService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinChallengeService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinCycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinMemberService.java
  backend/smody/src/main/java/com/woowacourse/smody/util/PagingUtil.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
Labels: 백엔드, 리팩터링

#247 feat: (fe) 기존 API 수정 및 인증 페이지에서도 색상과 함께 이모지가 나오게 구현
  frontend/src/Router.tsx
  frontend/src/apis/challengeApi/type.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/components/CardBox/CardBox.stories.tsx
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CardBox/type.ts
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertItem/type.ts
  frontend/src/components/CertItem/useCertItem.ts
  frontend/src/components/ChallengeDetail/index.tsx
  frontend/src/components/ChallengeDetail/type.ts
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeItem/type.ts
  frontend/src/mocks/data.ts
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/type.ts
  frontend/src/pages/CertFormPage/useCertFormPage.ts
  frontend/src/pages/CycleDetailPage/index.tsx
Labels: 프론트엔드, UI, API 연결

#251 feat: (fe) 웹푸시를 이용하여 알림 구독 기능 구현
  frontend/src/Router.tsx
  frontend/src/apis/constants.ts
  frontend/src/apis/pushNotificationApi/api.ts
  frontend/src/apis/pushNotificationApi/index.ts
  frontend/src/apis/pushNotificationApi/type.ts
  frontend/src/assets/bell_empty_icon.svg
  frontend/src/assets/bell_filled_icon.svg
  frontend/src/components/Bell/Bell.stories.tsx
  frontend/src/components/Bell/index.tsx
  frontend/src/components/Bell/type.ts
  frontend/src/components/DarkModeButton/index.tsx
  frontend/src/components/Dropdown/Dropdown.stories.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Dropdown/type.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/SubscriptionButton/index.tsx
  frontend/src/components/SubscriptionButton/type.ts
  frontend/src/components/ToggleButton/ToggleButton.stories.tsx
  frontend/src/components/ToggleButton/index.tsx
  frontend/src/components/ToggleButton/type.ts
  frontend/src/components/index.ts
  frontend/src/hooks/useImageInput.tsx
  frontend/src/hooks/useSubscribe.ts
  frontend/src/index.tsx
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/push.js
  frontend/src/pages/TestPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/pushStatus.ts
  frontend/src/utils/index.ts
Labels: 프론트엔드, API 연결, UI 로직, PWA

#253 feature : (be) 관리자 페이지 최신화
  backend/smody/src/main/java/com/woowacourse/smody/repository/CycleDetailRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/MenuLayout.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/ChallengeView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/CycleDetailView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/service/VaadinCycleDetailService.java
Labels: 백엔드

#250 feature: (be) 사이클 인증 시간 관련 web push 기능 구현
  backend/smody/build.gradle
  backend/smody/src/docs/asciidoc/api.adoc
  backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/PushSubscriptionController.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Progress.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/PushNotification.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/PushStatus.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/PushSubscription.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/SubscriptionRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/UnSubscriptionRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/VapidPublicKeyResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
  backend/smody/src/main/java/com/woowacourse/smody/push/PushResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/push/PushScheduler.java
  backend/smody/src/main/java/com/woowacourse/smody/push/PushSchedulerExecutor.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/CycleProgressPushEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/CycleProgressPushHandler.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/SubscriptionPushEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/SubscriptionPushHandler.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/PushNotificationRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/PushSubscriptionRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/PushSubscriptionService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/WebPushService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/AdminSecurityConfig.java
  backend/smody/src/main/resources/static/docs/api.html
  backend/smody/src/test/java/com/woowacourse/smody/IntegrationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/SmodyApplicationTests.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/PushSubscriptionControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/PushSchedulerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/CycleProgressPushHandlerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushHandlerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/repository/PushSubscriptionRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/ChallengeServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/OauthServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/PushSubscriptionServiceTest.java
  backend/smody/src/test/resources/application.properties
Labels: 백엔드, API 구현, PWA

#255 fix : (be) 캐스팅 수정
  backend/smody/src/main/java/com/woowacourse/smody/auth/AuthInterceptor.java
Labels: 백엔드, 에러 해결

#254 feat: (fe) 챌린지 검색 기능 구현
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/ChallengeList/type.ts
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/SearchBar/SearchBar.stories.tsx
  frontend/src/components/SearchBar/index.tsx
  frontend/src/components/SearchBar/type.ts
  frontend/src/components/index.ts
  frontend/src/hooks/useInput.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/useSearchPage.ts
Labels: 프론트엔드, UI, API 연결, UI 로직

#258 fix : 필드값이 null인 에러 수정
  backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
Labels: 백엔드, 에러 해결

#261 fix : 필드값 매핑 추가
  backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengeTabResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengesResponse.java
Labels: 백엔드, 에러 해결

#262 fix : OPTIONS 메소드 통과하도록 인터셉터 수정
  backend/smody/src/main/java/com/woowacourse/smody/auth/AuthInterceptor.java
Labels: 백엔드, 에러 해결

#263 fix : 시큐리티 해제 url 추가
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/AdminSecurityConfig.java
Labels: 백엔드, 에러 해결

#264 fix: (be) 피드 전체 조회 시 쿼리 스트링 값이 전달되지 않은 에러
  backend/smody/src/main/java/com/woowacourse/smody/dto/FeedRequest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/FeedAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/FeedControllerTest.java
Labels: 에러 해결

#259 fix: (fe) 챌린지 생성 api 보내는 key값 변경 및 챌린지 도전자 목록 출력 문제 해결
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/pages/ChallengeCreatePage/useChallengeCreatePage.ts
Labels: 프론트엔드, 에러 해결, API 연결

#257 feat: (fe) 댓글 컴포넌트 개발 및 피드 상세보기 페이지 API 연결
  frontend/src/Router.tsx
  frontend/src/apis/constants.ts
  frontend/src/apis/feedApi/api.ts
  frontend/src/apis/feedApi/index.ts
  frontend/src/apis/feedApi/type.ts
  frontend/src/commonType.ts
  frontend/src/components/CommentInput/CommentInput.stories.tsx
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CommentInput/type.ts
  frontend/src/components/CommentInput/useCommentInput.ts
  frontend/src/components/CommentItem/CommentItem.stories.tsx
  frontend/src/components/CommentItem/index.tsx
  frontend/src/components/CommentItem/type.ts
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/FeedItem/type.ts
  frontend/src/components/FeedItem/useFeedItem.ts
  frontend/src/components/index.ts
  frontend/src/constants/domain.ts
  frontend/src/constants/path.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/feed.js
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/FeedDetailPage/index.tsx
  frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts
  frontend/src/pages/index.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: 프론트엔드, UI, API 연결

#265 fix : 멤버 삭제 시 알람도 같이 삭제되도록 수정
  backend/smody/src/main/java/com/woowacourse/smody/repository/PushNotificationRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/PushSubscriptionRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/MemberService.java
  backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java
Labels: 백엔드, 에러 해결

#266 fix: (fe) 피드 전체 조회 API 정렬 기준 변경
  frontend/src/apis/constants.ts
  frontend/src/apis/feedApi/api.ts
  frontend/src/components/CommentItem/index.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/mocks/data.ts
Labels: 프론트엔드, 에러 해결

#269 fix: ios에서 Notification Api가 없음에 따른 에러 해결
  frontend/src/pushStatus.ts
Labels: 프론트엔드, 에러 해결

#272 feat: (fe) script 실행 명령어 추가
  frontend/package.json
  frontend/src/index.tsx
  frontend/webpack.config.js
Labels: 프론트엔드, 환경 설정

#274 fix : (be) 커서페이징 이슈 해결
  backend/smody/src/main/java/com/woowacourse/smody/dto/FeedRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/service/FeedQueryService.java
Labels: 에러 해결

#283 feat: (fe) FixedButton과 Snackbar 겹침 해결
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/FixedButton/index.tsx
  frontend/src/components/SnackBar/index.tsx
Labels: 프론트엔드, UI

#296 fix: (fe) 챌린지 검색 시 발생하는 에러 해결
  frontend/src/pages/SearchPage/useSearchPage.ts
Labels: 프론트엔드, 에러 해결

#293 feat: (fe) 사이클 생성 시 기준 시간 정하는 기능 구현 및 API 연결
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/components/BottomSheet/index.tsx
  frontend/src/components/BottomSheet/type.ts
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeItem/type.ts
  frontend/src/components/ChallengeItem/useChallengeItem.ts
  frontend/src/components/CustomCycleTimeBottomSheet/CustomCycleTimeBottomSheet.stories.tsx
  frontend/src/components/CustomCycleTimeBottomSheet/index.tsx
  frontend/src/components/CustomCycleTimeBottomSheet/type.ts
  frontend/src/components/CustomCycleTimeBottomSheet/useCustomCycleTimeBottomSheet.ts
  frontend/src/components/SuccessModal/useSuccessModal.ts
  frontend/src/components/index.ts
  frontend/src/hooks/useJoinChallenge.ts
  frontend/src/hooks/usePostJoinChallenge.ts
  frontend/src/pages/ChallengeCreatePage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/useChallengeDetailPage.ts
  frontend/src/utils/index.ts
Labels: 프론트엔드, UI, API 연결, UI 로직

#278 fix: (fe) 도전 중인 챌린지가 없을 때 CertPage에 EmptyContent 렌더링
  frontend/src/pages/CertPage/index.tsx
Labels: 프론트엔드, 에러 해결

#303 design: (fe) challengeName을 underline으로 표시
  frontend/src/components/CustomCycleTimeBottomSheet/index.tsx
  frontend/src/components/UnderLineText/index.tsx
Labels: 프론트엔드, UI

#299 feature: (be) 나의 알림 조회 및 읽은 알림 삭제 기능 구현
  backend/smody/src/docs/asciidoc/api.adoc
  backend/smody/src/main/java/com/woowacourse/smody/auth/GoogleApi.java
  backend/smody/src/main/java/com/woowacourse/smody/auth/LoginMemberArgumentResolver.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/PushNotificationController.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Progress.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/PushCase.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/PushNotification.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/PushNotificationResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/PushResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
  backend/smody/src/main/java/com/woowacourse/smody/push/PushResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/push/PushScheduler.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushCase.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushEventHandler.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/ChallengePushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/PushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/SubscriptionPushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/PushNotificationRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/PushNotificationService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/PushSubscriptionService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/WebPushService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/AdminSecurityConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/PushNotificationView.java
  backend/smody/src/main/resources/static/docs/api.html
  backend/smody/src/test/java/com/woowacourse/smody/ResourceFixture.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/PushNotificationControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/domain/PushNotificationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/PushSchedulerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventHandlerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/ChallengePushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/SubscriptionPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/PushNotificationServiceTest.java
Labels: 백엔드, 리팩터링, API 구현, PWA

#294 feat : (be) 댓글 기능 구현
  backend/smody/src/docs/asciidoc/api.adoc
  backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/CommentController.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/AuditingEntity.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Comment.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/CycleDetail.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Feed.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/CommentResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/CommentUpdateRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/FeedResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/CommentRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/FeedRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CommentQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CommentService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/FeedQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/FeedService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/AdminSecurityConfig.java
  backend/smody/src/test/java/com/woowacourse/smody/ResourceFixture.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/AcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/CommentAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/CommentControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/domain/CommentTest.java
  backend/smody/src/test/java/com/woowacourse/smody/repository/CycleDetailRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/repository/FeedRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CommentQueryServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CommentServiceTest.java
Labels: API 구현

#309 feat: (fe) 페이지 공유 기능 추가
  frontend/src/assets/share_icon.svg
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/ChallengeDetail/index.tsx
  frontend/src/components/ChallengeDetail/type.ts
  frontend/src/components/FixedButton/index.tsx
  frontend/src/components/ShareButton/index.tsx
  frontend/src/components/Title/index.tsx
  frontend/src/components/Title/type.ts
  frontend/src/components/index.ts
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/CycleDetailPage/index.tsx
Labels: 프론트엔드, PWA

#311 feat: (fe) Feed에 반응형 디자인 적용(grid)
  frontend/src/components/@shared/Text/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/Challenger/index.tsx
  frontend/src/components/CycleDetailItem/index.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/SuccessModal/useSuccessModal.ts
  frontend/src/pages/FeedPage/index.tsx
Labels: 프론트엔드, UI

#314 feat: (fe) 웹팩 빌드 시 public 폴더 내 파일들을 복사하여 dist 폴더에 넣기
  frontend/webpack.config.js
Labels: 프론트엔드

#316 test : (be) 테스트 픽스처 수정
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/test/java/com/woowacourse/smody/ResourceFixture.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/OauthAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/OauthControllerTest.java
Labels: 백엔드, 테스트

#317 feat: open graph meta tag 추가
  frontend/public/index.html
  frontend/src/components/ShareButton/index.tsx
Labels: 프론트엔드, UI, PWA

#302 feat: (fe) 댓글 수정 및 삭제 기능 구현
  frontend/src/apis/feedApi/api.ts
  frontend/src/apis/feedApi/index.ts
  frontend/src/apis/feedApi/type.ts
  frontend/src/assets/more.svg
  frontend/src/commonType.ts
  frontend/src/components/CommentInput/CommentInput.stories.tsx
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CommentInput/type.ts
  frontend/src/components/CommentInput/useCommentInput.ts
  frontend/src/components/CommentItem/index.tsx
  frontend/src/components/CommentItem/type.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/mocks/handlers/feed.js
  frontend/src/mocks/utils.js
  frontend/src/pages/FeedDetailPage/index.tsx
  frontend/src/pages/FeedDetailPage/type.ts
  frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts
Labels: 프론트엔드, UI, API 연결, UI 로직

#318 fix : (be) setter 추가
  backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengeOfMineRequest.java
Labels: 백엔드, 에러 해결

#320 design: (fe) Feed UI 수정
  frontend/src/components/FeedItem/index.tsx
Labels: 프론트엔드, UI

#321 feat: (be) 댓글이 달렸을 때 알림 전송 기능 구현
  backend/smody/src/main/java/com/woowacourse/smody/domain/PushCase.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/CommentPushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CommentService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/test/java/com/woowacourse/smody/ResourceFixture.java
  backend/smody/src/test/java/com/woowacourse/smody/push/PushSchedulerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/ChallengePushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/CommentPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/SubscriptionPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/PushSubscriptionServiceTest.java
Labels: 백엔드, PWA

#327 feature:(be) 자신의 피드에 댓글을 달면 알림 저장 안되도록 구현
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/CommentPushStrategy.java
  backend/smody/src/main/resources/static/docs/api.html
  backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/CommentPushStrategyTest.java
Labels: 백엔드, PWA

#329 feat : (be) 페이징 쿼리스트링 수정
  backend/smody/src/main/java/com/woowacourse/smody/auth/LoginMemberArgumentResolver.java
  backend/smody/src/main/java/com/woowacourse/smody/auth/TokenChekcerArgumentResolver.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/CommentController.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/CycleController.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/FeedController.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/MemberController.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/PushNotificationController.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/PagingParams.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengeOfMineRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/CommentUpdateRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/FeedRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/FilteredCycleHistoryResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/PushNotificationResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/PushResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushEvent.java
  backend/smody/src/main/java/com/woowacourse/smody/push/event/PushEventListener.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/ChallengePushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/CommentPushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/push/strategy/SubscriptionPushStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/ChallengeRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/DynamicCycleRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/DynamicCycleRepositoryImpl.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/PushNotificationRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CommentQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CommentService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/FeedQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/MemberService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/OauthService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/PushNotificationService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/PushSubscriptionService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/WebPushService.java
  backend/smody/src/test/java/com/woowacourse/smody/ResourceFixture.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/CommentAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/OauthAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ChallengeControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/CycleControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/FeedControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/MemberControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/OauthControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/PushNotificationControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/domain/PushNotificationTest.java
  backend/smody/src/test/java/com/woowacourse/smody/image/SmodyImageStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/PushSchedulerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventListenerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/ChallengePushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/CommentPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/strategy/SubscriptionPushStrategyTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/ChallengeServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/FeedQueryServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/PushNotificationServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/PushSubscriptionServiceTest.java
Labels: API 구현

#328 fix: 프로필 편집 완료 후 refetch되지 않던 문제 해결
  frontend/src/apis/oAuthApi/type.ts
  frontend/src/pages/ProfileEditPage/index.tsx
Labels: 프론트엔드, 에러 해결

#333 fix: (be) Member에 변경감지 필터링 적용
  backend/smody/src/main/java/com/woowacourse/smody/domain/Member.java
  backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java
Labels: 백엔드, 에러 해결

#338 feat: web-push 알림 받으면 setAppBadge하도록 서비스워커 통신 활성화
  frontend/public/manifest.json
  frontend/public/pushServiceWorker.js
  frontend/src/components/Header/useHeader.ts
Labels: 프론트엔드, PWA

#339 fix : (be) 마지막 원소의 id의 기본값을 갖도록 수정
  backend/smody/frontend/generated/vaadin.ts
  backend/smody/package-lock.json
  backend/smody/src/main/java/com/woowacourse/smody/domain/PagingParams.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/webpack.generated.js
  backend/smody/yarn.lock
Labels: 백엔드, 에러 해결

#340 fix : 정렬의 기본값을 갖도록 수정
  backend/smody/frontend/generated/vaadin.ts
  backend/smody/package-lock.json
  backend/smody/src/main/java/com/woowacourse/smody/repository/DynamicCycleRepositoryImpl.java
  backend/smody/webpack.generated.js
Labels: 백엔드, 에러 해결

#335 feat: (fe) 프로필 페이지에서 참가한 챌린지에 대한 사이클 리스트 보여주는 화면 구현
  frontend/package.json
  frontend/src/Layout/index.tsx
  frontend/src/Router.tsx
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/apis/constants.ts
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/commonType.ts
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CardBox/type.ts
  frontend/src/components/CardBox/useCardBox.ts
  frontend/src/components/ChallengeInfoWithUser/ChallengeInfoWithUser.stories.tsx
  frontend/src/components/ChallengeInfoWithUser/index.tsx
  frontend/src/components/ChallengeInfoWithUser/useChallengeInfoWithUser.ts
  frontend/src/components/CycleRecords/index.tsx
  frontend/src/components/CycleRecords/useCycleRecords.ts
  frontend/src/components/InfiniteScroll/index.tsx
  frontend/src/components/Record/Record.stories.tsx
  frontend/src/components/Record/index.tsx
  frontend/src/components/Record/type.ts
  frontend/src/components/Record/useRecord.ts
  frontend/src/components/Record/useRecordItem.ts
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/useMatchPath.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengeRecordsPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/utils/index.ts
  frontend/yarn.lock
Labels: 프론트엔드, UI, API 연결, UI 로직

#342 feat: (fe) 프로필에서 진행중인 챌린지 UI 및 수정된 API 연결
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/apis/constants.ts
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CardBox/type.ts
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/CardGridContainer/useCardGridContainer.ts
Labels: 프론트엔드, UI, API 연결, UI 로직

#346 feat: QA 피드백 UI 반영
  frontend/src/Layout/index.tsx
  frontend/src/apis/oAuthApi/index.ts
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CardGridContainer/useCardGridContainer.ts
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertItem/useCertItem.ts
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengerList/useChallengerList.ts
  frontend/src/components/CommentItem/index.tsx
  frontend/src/components/CustomCycleTimeBottomSheet/index.tsx
  frontend/src/components/CycleDetailItem/index.tsx
  frontend/src/components/CycleDetailList/index.tsx
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/pages/CertPage/useCertPage.ts
  frontend/src/pages/ChallengeDetailPage/useChallengeDetailPage.ts
  frontend/src/pages/CycleDetailPage/useCycleDetailPage.ts
  frontend/src/pages/FeedDetailPage/index.tsx
  frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts
  frontend/src/pages/FeedPage/useFeedPage.ts
  frontend/src/pages/SearchPage/useSearchPage.ts
  frontend/src/queryClient.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/validator.ts
Labels: 프론트엔드, UI

#345 feat: (fe) 챌린지에 대한 내 사이클 상세보기 페이지에서 전체, 성공 필터 버튼 구현
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/components/CycleRecords/index.tsx
  frontend/src/components/CycleRecords/type.ts
  frontend/src/components/CycleRecords/useCycleRecordList.ts
  frontend/src/components/CycleRecords/useCycleRecords.ts
Labels: 프론트엔드, UI, API 연결, UI 로직

#347 feat: 추가적인 디자인 수정
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/Title/index.tsx
  frontend/src/pages/CycleDetailPage/index.tsx
Labels: 프론트엔드, UI

#348 fix : (be) 피드 조회 시 cursorId가 0으로 올 때 발생하는 에러 처리
  backend/smody/src/main/java/com/woowacourse/smody/service/FeedQueryService.java
Labels: 백엔드, 에러 해결

#349 feat: (fe) 이모지 추가
  frontend/src/constants/style.ts
Labels: 프론트엔드, UI

#344 feat: (fe) ErrorBoundary를 이용한 에러처리 적용
  frontend/src/App.tsx
  frontend/src/Layout/index.tsx
  frontend/src/Router.tsx
  frontend/src/apis/constants.ts
  frontend/src/apis/oAuthApi/api.ts
  frontend/src/apis/oAuthApi/index.ts
  frontend/src/apis/oAuthApi/type.ts
  frontend/src/components/Bell/index.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Dropdown/type.ts
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/components/ErrorBoundary/type.ts
  frontend/src/components/ErrorFallbackHeader/index.tsx
  frontend/src/components/ErrorFallbackHeader/type.ts
  frontend/src/components/ErrorFallbackHeader/useErrorFallbackHeader.ts
  frontend/src/components/ErrorFallbackLoginButton/index.tsx
  frontend/src/components/ErrorFallbackLoginButton/type.ts
  frontend/src/components/ErrorFallbackMain/index.tsx
  frontend/src/components/ErrorFallbackMain/type.ts
  frontend/src/components/ErrorFallbackNotificationMessage/index.tsx
  frontend/src/components/ErrorFallbackNotificationMessage/type.ts
  frontend/src/components/ErrorFallbackNotificationMessage/useErrorFallbackNotificationMessage.ts
  frontend/src/components/ErrorFallbackSubscriptionButton/index.tsx
  frontend/src/components/ErrorFallbackSubscriptionButton/type.ts
  frontend/src/components/ErrorFallbackSubscriptionButton/useErrorFallbackSubscriptionButton.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/useHeader.ts
  frontend/src/components/Header/useHeaderRightButton.ts
  frontend/src/components/Header/useLoginButton.ts
  frontend/src/components/LandingNavigation/index.tsx
  frontend/src/components/NotificationMessage/index.tsx
  frontend/src/components/NotificationMessage/type.ts
  frontend/src/components/NotificationMessage/useNotificationMessage.ts
  frontend/src/components/PrivateOutlet/index.tsx
  frontend/src/components/SubscriptionButton/index.tsx
  frontend/src/components/SubscriptionButton/type.ts
  frontend/src/components/index.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/challenge.js
  frontend/src/mocks/handlers/feed.js
  frontend/src/mocks/handlers/push.js
  frontend/src/recoil/auth/atoms.ts
  frontend/src/recoil/auth/selectors.ts
  frontend/src/recoil/auth/type.ts
Labels: 프론트엔드, API 연결

#351 feat: (fe) 검색 바 상단에 고정시키도록 구현
  frontend/src/components/SearchBar/index.tsx
  frontend/src/pages/SearchPage/index.tsx
Labels: 프론트엔드, UI, UI 로직

#354 fix: (fe) unsubscribe api 에러 해결
  frontend/src/apis/pushNotificationApi/api.ts
  frontend/src/hooks/useSubscribe.ts
Labels: 프론트엔드, API 연결

#362 fix: (fe) 로그아웃 처리 에러 범위 확대 및 새로 고침 시 알림 표시 이슈 해결
  frontend/src/components/Dropdown/Dropdown.stories.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Dropdown/type.ts
  frontend/src/components/Dropdown/useDropdown.ts
  frontend/src/components/ErrorFallbackHeader/index.tsx
  frontend/src/components/ErrorFallbackHeader/type.ts
  frontend/src/components/ErrorFallbackHeader/useErrorFallbackHeader.ts
  frontend/src/components/ErrorFallbackMain/index.tsx
  frontend/src/components/ErrorFallbackNotificationMessage/useErrorFallbackNotificationMessage.ts
  frontend/src/components/ErrorFallbackSubscriptionButton/useErrorFallbackSubscriptionButton.ts
  frontend/src/components/FeedItem/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/index.ts
Labels: 프론트엔드, 에러 해결

#365 fix: (fe) 알림 버튼 클릭 전 알림 개수 뱃지 안 보이는 이슈 해결
  frontend/src/components/Dropdown/useDropdown.ts
Labels: 프론트엔드, 에러 해결

#369 feat: (fe) header와 search-bar 디자인 변경
  frontend/src/Layout/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/SearchBar/index.tsx
  frontend/src/pages/SearchPage/index.tsx
Labels: 프론트엔드, UI

#368 feat: 페이지 이동시 스크롤을 상단으로 초기화
  frontend/src/Layout/index.tsx
  frontend/src/components/ScrollToTop/index.tsx
  frontend/src/components/ScrollToTop/type.ts
  frontend/src/components/index.ts
Labels: 프론트엔드, UI, UI 로직

#370 design: (fe) height 변경
  frontend/src/Layout/index.tsx
Labels: 프론트엔드, UI

#373 doc: 기술스택 추가
  README.md
Labels: 문서화
