Repository woowacourse-teams/2022-smody, pull requests merged in 2022-07, with the labels that each got.

#11 feat: ( fe) 회원가입 페이지 구현
  frontend/.eslintrc.js
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/.storybook/storybook.d.ts
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/assets/correct_icon.svg
  frontend/src/assets/email_icon.svg
  frontend/src/assets/incorrect_icon.svg
  frontend/src/assets/person_icon.svg
  frontend/src/assets/pw_icon.svg
  frontend/src/commonType.ts
  frontend/src/components/@shared/FlexBox/index.tsx
  frontend/src/components/@shared/FlexBox/type.ts
  frontend/src/components/@shared/Text/Text.stories.tsx
  frontend/src/components/@shared/Text/index.tsx
  frontend/src/components/@shared/Text/type.ts
  frontend/src/components/AuthInput/AuthInput.stories.tsx
  frontend/src/components/AuthInput/index.tsx
  frontend/src/components/AuthInput/type.ts
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/Button/type.ts
  frontend/src/components/LinkText/LinkText.stories.tsx
  frontend/src/components/LinkText/index.tsx
  frontend/src/components/LinkText/type.ts
  frontend/src/components/Logo/Logo.stories.tsx
  frontend/src/components/Logo/index.tsx
  frontend/src/components/Logo/type.ts
  frontend/src/components/ValidationMessage/index.tsx
  frontend/src/components/ValidationMessage/type.ts
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/global.d.ts
  frontend/src/hooks/useInput.ts
  frontend/src/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/NotFoundPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/color.ts
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
  frontend/src/styles/type.ts
  frontend/src/utils/validator.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 프론트엔드

#12 feat: Login 페이지 구현
  frontend/src/assets/visibility_icon.svg
  frontend/src/components/AuthInput/index.tsx
  frontend/src/components/AuthInput/type.ts
  frontend/src/components/VisibilityIcon/index.tsx
  frontend/src/components/VisibilityIcon/type.ts
  frontend/src/hooks/useInput.ts
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/utils/validator.ts
Labels: 프론트엔드

#14 feat: (fe) 레이아웃 구현
  frontend/.storybook/storybook.d.ts
  frontend/src/Layout/index.tsx
  frontend/src/Router.tsx
  frontend/src/assets/home.svg
  frontend/src/assets/plus.svg
  frontend/src/assets/profile.svg
  frontend/src/assets/search.svg
  frontend/src/components/AuthInput/index.tsx
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/LinkText/LinkText.stories.tsx
  frontend/src/components/LinkText/index.tsx
  frontend/src/components/LinkText/type.ts
  frontend/src/components/Logo/Logo.stories.tsx
  frontend/src/components/Logo/index.tsx
  frontend/src/components/Logo/type.ts
  frontend/src/components/Navbar/NavBar.stories.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Navbar/type.ts
  frontend/src/components/ValidationMessage/ValidationMessage.stories.tsx
  frontend/src/components/index.ts
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
Labels: 프론트엔드

#18 feat: (fe) 인증 페이지 구현
  frontend/src/Router.tsx
  frontend/src/commonType.ts
  frontend/src/components/@shared/Text/index.tsx
  frontend/src/components/@shared/Text/type.ts
  frontend/src/components/CertItem/CertItem.stories.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CheckCircles/CheckCircles.stories.tsx
  frontend/src/components/CheckCircles/index.tsx
  frontend/src/components/CheckCircles/type.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Timer/Timer.stories.tsx
  frontend/src/components/Timer/index.tsx
  frontend/src/components/Timer/type.ts
  frontend/src/components/UnderLineText/UnderLineText.stories.tsx
  frontend/src/components/UnderLineText/index.tsx
  frontend/src/components/UnderLineText/type.ts
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/mock/data.ts
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/styles/type.ts
  frontend/src/utils/index.ts
Labels: 프론트엔드, UI, UI 로직

#21 feat: 사용자 인증 API 연결
  frontend/.eslintrc.js
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/apis/apiClient.ts
  frontend/src/apis/authApi/api.ts
  frontend/src/apis/authApi/index.ts
  frontend/src/apis/authApi/type.ts
  frontend/src/apis/index.ts
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/constants/path.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.js
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/LoginPage/type.ts
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/recoil/auth/atoms.ts
  frontend/yarn.lock
Labels: 프론트엔드, API 연결

#24 feat: (fe) 챌린지 API 연결
  README.md
  frontend/.gitignore
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Router.tsx
  frontend/src/apis/apiClient.ts
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/assets/cute_cat_with_smody.png
  frontend/src/components/CertItem/CertItem.stories.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertItem/type.ts
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/ErrorBoundary/index.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/global.d.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/challenge.js
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/type.ts
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/yarn.lock
Labels: 프론트엔드, API 연결

#27 fix: (fe) 챌린지 사이클의 잘못된 시작 시간 수정
  frontend/src/pages/ChallengeDetailPage/index.tsx
Labels: 프론트엔드, 에러 해결

#28 docs: README 업데이트
  README.md
Labels: 문서화

#29 docs: 기술스택 아이콘 추가
  README.md
Labels: 문서화

#38 feat: (fe) 인증 완료 후 남은 시간 표시 방법 변경
  frontend/src/components/Timer/index.tsx
  frontend/src/components/Timer/useTimer.tsx
  frontend/src/constants/domain.ts
  frontend/src/mocks/data.ts
Labels: 프론트엔드, UI

#40 refactor: (be) 프로덕션 코드 리팩토링
  backend/smody/src/main/java/com/woowacourse/smody/auth/AuthInterceptor.java
  backend/smody/src/main/java/com/woowacourse/smody/auth/JwtTokenExtractor.java
  backend/smody/src/main/java/com/woowacourse/smody/auth/JwtTokenProvider.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/CycleController.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengeResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/CycleRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
Labels: 백엔드, 리팩터링

#42 feat: (be) 재도전 로직 구현
  backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Progress.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/test/java/com/woowacourse/smody/domain/CycleTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
Labels: 백엔드, API 구현

#46 feat: (be) 성공한 챌린지 조회 및 사이클 통계 정보 구현
  backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/CycleController.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Progress.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/StatResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/SuccessChallengeResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/repository/CycleRepository.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/util/PagingUtil.java
  backend/smody/src/main/resources/application.properties
  backend/smody/src/test/java/com/woowacourse/smody/controller/ChallengeControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/CycleControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/MemberControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/domain/CycleTest.java
  backend/smody/src/test/java/com/woowacourse/smody/repository/CycleRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/ChallengeServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
  backend/smody/src/test/resources/application.properties
Labels: 백엔드, API 구현

#59 refactor: (be) Cycle 마감 시간 급한 순으로 정렬하는 로직 리팩터링
  backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/test/java/com/woowacourse/smody/domain/CycleTest.java
Labels: 백엔드, 리팩터링

#62 refactor: (be) 구글 api 기능 분리 및 OAuthController 테스트
  backend/smody/src/main/java/com/woowacourse/smody/controller/OauthController.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/openapi/GoogleApi.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/MemberControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/OauthControllerTest.java
Labels: 백엔드, 리팩터링

#63 chore: (be) gitignore 수정
  backend/smody/.gitignore
  backend/smody/gradle/wrapper/gradle-wrapper.properties
Labels: 백엔드, 에러 해결

#67 fix: OAuth redirect_uri 변경
  backend/smody/src/main/java/com/woowacourse/smody/controller/openapi/GoogleApi.java
Labels: 에러 해결

#69 feat: (fe) 변경된 핵심 API를 UI에 연결
  frontend/src/apis/authApi/index.ts
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/apis/constants.ts
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/apis/index.ts
  frontend/src/apis/oAuthApi/api.ts
  frontend/src/apis/oAuthApi/index.ts
  frontend/src/apis/oAuthApi/type.ts
  frontend/src/commonType.ts
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/CertAuth/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertItem/type.ts
  frontend/src/components/CertUnAuth/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/SuccessModal/type.ts
  frontend/src/constants/domain.ts
  frontend/src/hooks/api/type.ts
  frontend/src/hooks/api/usePostJoinChallenge.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/type.ts
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/utils/index.ts
  frontend/tsconfig.json
Labels: 프론트엔드, API 연결, UI 로직

#72 chore : (be) properties 재설정
  backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/openapi/GoogleApi.java
  backend/smody/src/test/resources/data.sql
Labels: 백엔드, 인프라

#78 feat: (fe) BASE_URL 은닉화 기능 추가
  frontend/.gitignore
  frontend/package.json
  frontend/src/apis/apiClient.ts
  frontend/src/constants/path.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 프론트엔드, API 연결, UI 로직

#81 chore: (be) 데이터베이스 의존성 추가
  backend/smody/build.gradle
Labels: 백엔드, 인프라

#79 feat : (be) 챌린지 단건 조회, 전체 챌린지 조회 시 도전중인지 알려주는 기능 또는 분기 처리
  backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengeResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ChallengeControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/ChallengeServiceTest.java
Labels: 백엔드, API 구현

#80 feat: (fe) 로그인 여부 및 도전 여부에 따라 도전중 버튼 렌더링
  frontend/package.json
  frontend/src/apis/challengeApi/api.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/challengeApi/type.ts
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeItem/type.ts
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/challenge.js
  frontend/src/mocks/handlers/index.ts
Labels: 프론트엔드, API 연결

#84 chore: cors, redirect uri 변경
  backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/openapi/GoogleApi.java
Labels: 에러 해결, 환경 설정

#85 fix: (fe) oAuth redirection url을 백엔드에서 바로 받는 것으로 수정
  frontend/package.json
  frontend/src/components/CertUnAuth/index.tsx
  frontend/src/components/Header/index.tsx
Labels: 프론트엔드, 에러 해결

#90 refactor: (be) 서버 기준시간 설정 및 시간관리 통합
  backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
  backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
  backend/smody/src/main/java/com/woowacourse/smody/dto/CycleRequest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java
Labels: 에러 해결

#91 fix: (fe) 시간 및 성공 챌린지 에러 수정
  frontend/src/apis/cycleApi/api.ts
  frontend/src/apis/cycleApi/type.ts
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/hooks/api/usePostJoinChallenge.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/challenge.js
  frontend/src/mocks/handlers/index.ts
Labels: 프론트엔드, 에러 해결

#94 feat: (fe) 빈 컨텐츠 UI 구현
  frontend/src/assets/feed.svg
  frontend/src/assets/plus.svg
  frontend/src/assets/profile.svg
  frontend/src/assets/search.svg
  frontend/src/components/@shared/Text/index.tsx
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/CertAuth/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertUnAuth/index.tsx
  frontend/src/components/EmptyContent/EmptyContent.stories.tsx
  frontend/src/components/EmptyContent/index.tsx
  frontend/src/components/EmptyContent/type.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/LinkText/type.ts
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/UnderLineText/index.tsx
  frontend/src/components/index.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/NotFoundPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/styles/type.ts
Labels: 프론트엔드, UI, 리팩터링

#95 feat: (fe) 스낵바 컴포넌트 구현
  README.md
  frontend/public/index.html
  frontend/src/Layout/index.tsx
  frontend/src/Router.tsx
  frontend/src/apis/authApi/api.ts
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/CertAuth/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/SnackBar/SnackBar.stories.tsx
  frontend/src/components/SnackBar/index.tsx
  frontend/src/components/SnackBar/type.ts
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/api/type.ts
  frontend/src/hooks/api/usePostJoinChallenge.ts
  frontend/src/hooks/useSnackBar.ts
  frontend/src/mocks/handlers/auth.js
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/pages/VocPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/recoil/snackbar/atoms.ts
  frontend/src/styles/color.ts
  frontend/src/styles/theme.ts
Labels: 프론트엔드, UI, UI 로직

#104 feat: (be) 웹 훅을 통한 자동배포 구현
  backend/smody/src/main/java/com/woowacourse/smody/webhook/GitHubHookRequest.java
  backend/smody/src/main/java/com/woowacourse/smody/webhook/WebHookController.java
Labels: 백엔드, 환경 설정, 인프라

#106 feat: (fe) 무한 스크롤 기능 구현
  frontend/src/Layout/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/LoadingSpinner/index.tsx
  frontend/src/components/SnackBar/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/hooks/api/usePostJoinChallenge.ts
  frontend/src/hooks/useIntersect.ts
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengeDetailPage/index.tsx
Labels: 프론트엔드, UI 로직

#107 feat: (fe) 유효하지 않은 accessToken의 경우 accessToken 제거 및 로그아웃
  frontend/src/Router.tsx
  frontend/src/apis/authApi/index.ts
  frontend/src/apis/challengeApi/index.ts
  frontend/src/apis/cycleApi/index.ts
  frontend/src/apis/oAuthApi/index.ts
  frontend/src/commonType.ts
  frontend/src/components/CertAuth/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/hooks/api/usePostJoinChallenge.ts
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/recoil/auth/atoms.ts
  frontend/src/recoil/auth/selectors.ts
  frontend/src/utils/validator.ts
Labels: 프론트엔드, 에러 해결, UI 로직

#108 feat: (fe) 유효하지 않은 accessToken의 경우 accessToken 제거 및 로그아웃 해결
  frontend/src/Router.tsx
  frontend/src/apis/challengeApi/index.ts
  frontend/src/components/CertAuth/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/hooks/api/usePostJoinChallenge.ts
  frontend/src/hooks/useManageAccessToken.ts
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/recoil/auth/atoms.ts
  frontend/src/recoil/auth/selectors.ts
  frontend/src/utils/validator.ts
Labels: 프론트엔드, 에러 해결, UI 로직

#111 fix: (fe) 챌린지 목록 페이지 새로고침 시 '도전중'이 풀리는 상태 수정
  frontend/src/apis/challengeApi/index.ts
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/hooks/useManageAccessToken.ts
Labels: 프론트엔드, 에러 해결

#113 feat: (fe) 배포 전 프론트엔드 에러 해결 및 대단한 개선
  frontend/src/components/CardGridContainer/index.tsx
  frontend/src/components/CertAuth/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/CertUnAuth/index.tsx
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/LoadingSpinner/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/api/usePostJoinChallenge.ts
  frontend/src/hooks/useGoogleLogin.ts
  frontend/src/hooks/useManageAccessToken.ts
  frontend/src/mocks/data.ts
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/pages/VocPage/index.tsx
  frontend/src/utils/emoji.js
Labels: 프론트엔드, 에러 해결

#116 fix: (fe) 재도전했을 때 재도전한 챌린지가 바로 보이지 않는 에러
  frontend/src/components/ChallengeItem/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/hooks/api/type.ts
  frontend/src/hooks/api/usePostJoinChallenge.ts
Labels: 프론트엔드, 에러 해결

#139 feat: (be) Service 계층 CQS 리팩터링
  backend/smody/src/docs/asciidoc/api.adoc
  backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
  backend/smody/src/main/java/com/woowacourse/smody/controller/CycleController.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleQueryService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
  backend/smody/src/main/java/com/woowacourse/smody/service/MemberService.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/AdminSecurityConfig.java
  backend/smody/src/main/resources/static/docs/api.html
  backend/smody/src/test/java/com/woowacourse/smody/controller/ChallengeControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/CycleControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/controller/MemberControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/ChallengeServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
  backend/smody/yarn.lock
Labels: 백엔드, 리팩터링, 최적화

#144 프로필 편집 페이지 구현
  frontend/src/App.tsx
  frontend/src/Layout/index.tsx
  frontend/src/Router.tsx
  frontend/src/apis/oAuthApi/api.ts
  frontend/src/apis/oAuthApi/index.ts
  frontend/src/apis/oAuthApi/type.ts
  frontend/src/commonType.ts
  frontend/src/components/AuthInput/AuthInput.stories.tsx
  frontend/src/components/CertAuth/index.tsx
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/type.ts
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/Input/type.ts
  frontend/src/components/LandingNavigation/index.tsx
  frontend/src/components/PrivateOutlet/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/ValidationMessage/type.ts
  frontend/src/components/index.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useInput.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/auth.js
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/LoginPage/type.ts
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/utils/index.ts
  frontend/src/utils/validator.ts
Labels: 프론트엔드, UI, API 연결, UI 로직

#146 refactor: (fe) API 에러 핸들링을 중앙 집중식으로 리팩터링
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/apis/oAuthApi/index.ts
  frontend/src/components/CardBox/index.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/ChallengeList/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/constants/message.ts
  frontend/src/hooks/api/usePostJoinChallenge.ts
  frontend/src/hooks/auth/useAuth.ts
  frontend/src/hooks/useGoogleLogin.ts
  frontend/src/hooks/useManageAccessToken.ts
  frontend/src/hooks/useQueryErrorHandler.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/CertPage/index.tsx
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/ProfileEditPage/index.tsx
  frontend/src/queryClient.ts
  frontend/src/styles/color.ts
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
Labels: 프론트엔드, 리팩터링, API 연결

#148 feat: (fe) MSW API mocking 추가
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/challenge.js
  frontend/src/pages/ChallengeDetailPage/index.tsx
  frontend/webpack.config.js
Labels: 프론트엔드

#149 feat: (fe) logo 및 챌린지 성공 시 애니메이션 추가
  frontend/package.json
  frontend/src/components/CertItem/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Logo/index.tsx
  frontend/src/components/Logo/type.ts
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/utils/index.ts
  frontend/yarn.lock
Labels: 프론트엔드, UI

#154 style: (be) 로그 색상 추가
  backend/smody/frontend/generated/vaadin.ts
  backend/smody/package-lock.json
  backend/smody/src/main/java/com/woowacourse/smody/controller/MemberController.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/LogLevel.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/LogView.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/domain/DomainView.java
  backend/smody/webpack.generated.js
  backend/smody/yarn.lock
Labels: 백엔드, 리팩터링, UI 로직, 문서화

#157 fix: (fe) 로그인 후 Home에서 로그인 버튼 보이는 문제 해결
  frontend/src/pages/LandingPage/index.tsx
Labels: 프론트엔드, 에러 해결

#158 fix: (be) 로그 로직 수정
  .gitignore
  backend/smody/.gitignore
  backend/smody/src/main/java/com/woowacourse/smody/logging/LogInterceptor.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/LogLevel.java
  backend/smody/src/main/java/com/woowacourse/smody/ui/admin/LogView.java
  backend/smody/src/main/resources/logback-spring.xml
Labels: 백엔드, 리팩터링, 에러 해결

#162 fix: (be) 오늘 로그 파일 이름 수정
  backend/smody/src/main/resources/logback-spring.xml
Labels: 백엔드, 리팩터링, 에러 해결

#164 feat: (fe) 회원 탈퇴 모달 구현
  frontend/src/components/@shared/ModalOverlay/index.tsx
  frontend/src/components/Profile/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/UserWithdrawalModal/index.tsx
  frontend/src/components/UserWithdrawalModal/type.ts
  frontend/src/components/index.ts
  frontend/src/pages/ProfileEditPage/index.tsx
Labels: 프론트엔드, UI
