Repository woowacourse-teams/2022-smody, pull requests merged in 2022-11, with the labels that each got.

#634 feat: (fe) webpack 설정 리팩터링(babel-loader 적용 및 최적화 등)
  frontend/.browserslistrc
  frontend/package.json
  frontend/webpack.config.js
  frontend/webpack/webpack.common.js
  frontend/webpack/webpack.dev.js
  frontend/webpack/webpack.prod.js
  frontend/yarn.lock
Labels: 프론트엔드, 리팩터링, 최적화, 환경 설정

#636 feat: (fe) Typescript Module README 수정
  frontend/lib/README.md
  frontend/lib/package.json
Labels: 프론트엔드

#639 feature: (fe) 웹 접근성 추가 개선
  frontend/src/components/CheckCircles/index.tsx
  frontend/src/components/DarkModeButton/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/Input/type.ts
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/SROnly/index.tsx
  frontend/src/components/SuccessModal/index.tsx
  frontend/src/components/Tabs/index.tsx
  frontend/src/components/Tabs/type.ts
  frontend/src/components/index.ts
  frontend/src/pages/ChallengePage/index.tsx
  frontend/src/pages/EventPage/index.tsx
  frontend/src/pages/FeedPage/index.tsx
  frontend/src/pages/PopularChallengePage/index.tsx
  frontend/src/pages/RandomChallengePage/index.tsx
  frontend/src/pages/SearchPage/index.tsx
Labels: 프론트엔드, 접근성

#632 test: (be) 인수 테스트 작성
  backend/smody/src/main/java/com/woowacourse/smody/challenge/controller/ChallengeController.java
  backend/smody/src/main/java/com/woowacourse/smody/challenge/domain/ChallengingRecords.java
  backend/smody/src/main/java/com/woowacourse/smody/comment/service/CommentService.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/controller/CycleController.java
  backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionUtils.java
  backend/smody/src/main/java/com/woowacourse/smody/image/strategy/ImgBBImageStrategy.java
  backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankManager.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/AcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/AcceptanceTestFixture.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/ChallengeAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/CommentAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/CycleAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/FeedAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/MemberAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/OauthAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/PushAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/RankingAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/controller/CycleControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/ProgressTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleRepositoryTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/exception/BindingExceptionTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/controller/MemberControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberApiServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/event/EventExceptionTest.java
  backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationApiServiceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/ranking/event/RankingEventExceptionTest.java
  backend/smody/src/test/java/com/woowacourse/smody/support/EventListenerMockTest.java
Labels: 백엔드, 테스트

#647 refactor: (fe) useInstallApp 리팩터링(conflict 해결)
  frontend/src/hooks/useInstallApp.ts
  frontend/src/pages/LandingPage/components/InstallPrompt/index.tsx
  frontend/src/utils/index.ts
Labels: 프론트엔드, 리팩터링, PWA

#645 feat: (be) 사이클 진척도 증가시 cycleDetailId 추가
  backend/smody/src/main/java/com/woowacourse/smody/cycle/dto/ProgressResponse.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleApiService.java
  backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
  backend/smody/src/main/resources/static/docs/api.html
  backend/smody/src/test/java/com/woowacourse/smody/acceptance/CycleAcceptanceTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/controller/CycleControllerTest.java
  backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleApiServiceTest.java
Labels: 백엔드, 리팩터링, API 구현

#646 refactor: (fe) CommentInput 컴포넌트에서 멘션 기능 MentionableInput을 분리하고 CertFormPage에도 멘션 기능 추가
  frontend/src/apis/cycleApi/type.ts
  frontend/src/components/MentionableInput/MembersPopover/MemberItem.tsx
  frontend/src/components/MentionableInput/MembersPopover/index.tsx
  frontend/src/components/MentionableInput/MembersPopover/type.ts
  frontend/src/components/MentionableInput/index.tsx
  frontend/src/components/MentionableInput/type.ts
  frontend/src/components/MentionableInput/useMentionableInput.ts
  frontend/src/components/MentionableInput/usePopover.ts
  frontend/src/components/index.ts
  frontend/src/pages/CertFormPage/index.tsx
  frontend/src/pages/CertFormPage/useCertFormPage.ts
  frontend/src/pages/FeedDetailPage/components/CommentInput/index.tsx
  frontend/src/pages/FeedDetailPage/components/CommentInput/useCommentInput.ts
Labels: 프론트엔드, UI, UI 로직

#651 fix: (fe) 테스트 코드 작동 정상화
  frontend/jest.config.ts
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/__test__/certPage.test.tsx
  frontend/src/__test__/profilePage.test.tsx
  frontend/src/__test__/searchPage.test.tsx
  frontend/src/setupTests.ts
  frontend/yarn.lock
Labels: 프론트엔드, 에러 해결, 테스트

#653 docs: README.md 업데이트
  README.md
Labels: 문서화

#655 feat: (fe) serviceworker 버전 업그레이드
  frontend/public/pwaServiceWorker.js
Labels: 프론트엔드

#656 Version 4.3.1 배포
  .github/workflows/frontend-ci.yml
  frontend/package.json
  frontend/public/pwaServiceWorker.js
Labels: 프론트엔드

#658 chore: (fe) Jest Coverage Comment를 github action 추가
  .github/workflows/frontend-ci.yml
  frontend/coverage/coverage-summary.json
  frontend/jest.config.ts
  frontend/package.json
  frontend/yarn.lock
Labels: 프론트엔드, 인프라, 테스트

#659 fix: (fe) Jest에서 svg 처리되지 않는 문제 등 테스트 코드 문제 해결
  frontend/.browserslistrc
  frontend/.gitignore
  frontend/jest.config.ts
  frontend/package.json
  frontend/src/__test__/certPage.test.tsx
  frontend/src/__test__/profilePage.test.tsx
  frontend/src/__test__/searchPage.test.tsx
  frontend/src/components/CertItem/index.tsx
  frontend/src/mocks/MockIntersectionObserver.ts
  frontend/src/setupTests.ts
  frontend/src/utils/testUtils.tsx
Labels: 프론트엔드, 에러 해결, 환경 설정, 테스트
